-- SQL Conceptual para Supabase (Usará UUIDs y TIMESTAMPTZ por defecto)
-- Versión 1.3 - Comentarios en Español. Identificadores en Inglés.

-- Perfiles de Administradores (Vinculado a Supabase Auth)
CREATE TABLE public.admin_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, -- Clave primaria es también FK a Supabase Auth
    full_name VARCHAR(255),
    -- Otros campos específicos si son necesarios (rol, etc.)
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
    -- Políticas RLS para asegurar que solo admins accedan/modifiquen perfiles
);
COMMENT ON TABLE public.admin_profiles IS 'Almacena información adicional del perfil para usuarios administradores, vinculada a auth.users de Supabase.';
COMMENT ON COLUMN public.admin_profiles.id IS 'Referencia al campo id en la tabla auth.users.';

-- Clientes Potenciales (Recopilados de encuestas, NO son usuarios autenticados en V1)
CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Equivalente a SERIAL en Supabase
    email VARCHAR(255) UNIQUE, -- Unicidad para futura agregación
    phone VARCHAR(50) UNIQUE,  -- Unicidad para futura agregación
    first_seen TIMESTAMPTZ DEFAULT now() NOT NULL,
    last_seen TIMESTAMPTZ DEFAULT now() NOT NULL
    -- En V.Next, esta tabla podría fusionarse o vincularse a auth.users si los clientes se loguean.
);
COMMENT ON TABLE public.customers IS 'Almacena información de contacto de clientes potenciales obtenida de las encuestas (usuarios no autenticados en V1). La unicidad en email/teléfono permite la agregación futura de perfiles.';
CREATE INDEX idx_customers_email ON public.customers(email) WHERE email IS NOT NULL;
CREATE INDEX idx_customers_phone ON public.customers(phone) WHERE phone IS NOT NULL;

-- Encuestas
CREATE TABLE public.surveys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL, -- Identificador amigable para URL
    description TEXT,
    requires_product_code BOOLEAN DEFAULT FALSE NOT NULL, -- Indica si se necesita un código de producto para acceder
    is_active BOOLEAN DEFAULT TRUE NOT NULL, -- Permite activar/desactivar encuestas
    discount_code_template VARCHAR(100) DEFAULT 'DESC{PERCENT}-{CODE}' NOT NULL, -- Plantilla para generar códigos de descuento. {PERCENT} y {CODE} son placeholders.
    discount_code_validity_days INT DEFAULT 30 NOT NULL CHECK (discount_code_validity_days >= 0), -- Días de validez del código generado
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.surveys IS 'Define la estructura y configuración de cada encuesta.';
COMMENT ON COLUMN public.surveys.name IS 'Nombre público de la encuesta.';
COMMENT ON COLUMN public.surveys.slug IS 'Identificador único usado en la URL para acceder a la encuesta.';
COMMENT ON COLUMN public.surveys.requires_product_code IS 'Si es TRUE, el cliente debe ingresar un código de producto válido para iniciar la encuesta.';
COMMENT ON COLUMN public.surveys.is_active IS 'Controla si la encuesta está disponible para los clientes.';
COMMENT ON COLUMN public.surveys.discount_code_template IS 'Plantilla para los códigos de descuento generados. Placeholders: {PERCENT}, {CODE}. Ejemplo: MI MARCA-{PERCENT}OFF-{CODE}.';
COMMENT ON COLUMN public.surveys.discount_code_validity_days IS 'Número de días durante los cuales el código de descuento generado es válido.';


-- Secciones de una Encuesta
CREATE TABLE public.survey_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    section_order INT NOT NULL, -- Orden numérico de la sección dentro de la encuesta
    discount_percentage_cumulative INT NOT NULL CHECK (discount_percentage_cumulative >= 0 AND discount_percentage_cumulative <= 100), -- % de descuento TOTAL acumulado al COMPLETAR esta sección
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    FOREIGN KEY (survey_id) REFERENCES public.surveys(id) ON DELETE CASCADE,
    UNIQUE (survey_id, section_order) -- Una sección solo puede tener un orden dentro de una encuesta
);
COMMENT ON TABLE public.survey_sections IS 'Representa las secciones ordenadas dentro de una encuesta, cada una potencialmente contribuyendo al descuento.';
COMMENT ON COLUMN public.survey_sections.survey_id IS 'Referencia a la encuesta a la que pertenece esta sección.';
COMMENT ON COLUMN public.survey_sections.section_order IS 'Determina el orden en que se muestra esta sección al cliente.';
COMMENT ON COLUMN public.survey_sections.discount_percentage_cumulative IS 'Porcentaje de descuento total acumulado si el usuario completa ESTA sección.';

-- Preguntas dentro de una Sección
CREATE TABLE public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    question_text TEXT NOT NULL, -- El texto de la pregunta
    question_type VARCHAR(50) NOT NULL CHECK (question_type IN ('text_short', 'text_long', 'radio', 'checkbox', 'scale', 'dropdown', 'email', 'phone', 'name')), -- Tipos de pregunta permitidos. Añadimos tipos específicos para datos de cliente.
    options JSONB NULL, -- Almacena las opciones para tipos radio, checkbox, scale, dropdown (ej: [{"value": "1", "label": "Malo"}, ...])
    is_required BOOLEAN DEFAULT FALSE NOT NULL, -- Indica si la pregunta debe ser respondida para completar la sección
    question_order INT NOT NULL, -- Orden numérico de la pregunta dentro de la sección
    -- map_to_customer_field VARCHAR(50) NULL, -- V.NEXT: Campo para indicar si esta pregunta mapea a un campo de la tabla 'customers' (ej: 'email', 'phone', 'name')
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    FOREIGN KEY (section_id) REFERENCES public.survey_sections(id) ON DELETE CASCADE,
    UNIQUE (section_id, question_order) -- Una pregunta solo puede tener un orden dentro de una sección
);
COMMENT ON TABLE public.questions IS 'Define las preguntas individuales dentro de una sección de la encuesta.';
COMMENT ON COLUMN public.questions.section_id IS 'Referencia a la sección a la que pertenece esta pregunta.';
COMMENT ON COLUMN public.questions.question_text IS 'El texto literal de la pregunta que verá el cliente.';
COMMENT ON COLUMN public.questions.question_type IS 'Define cómo se presenta la pregunta y qué tipo de respuesta se espera.';
COMMENT ON COLUMN public.questions.options IS 'Almacena opciones estructuradas (ej: opciones para radio/checkbox/dropdown, etiquetas de escala) en formato JSON.';
COMMENT ON COLUMN public.questions.is_required IS 'Si es TRUE, el cliente no puede marcar la sección como completa sin responder esta pregunta.';
COMMENT ON COLUMN public.questions.question_order IS 'Determina el orden en que se muestra esta pregunta dentro de la sección.';
-- COMMENT ON COLUMN public.questions.map_to_customer_field IS 'FUNCIONALIDAD V.NEXT: Vincula la respuesta de esta pregunta a un campo específico en la tabla de perfil del cliente.';

-- Lotes de Códigos de Producto
CREATE TABLE public.code_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL, -- Nombre descriptivo del lote (ej: "Lote Q1 2024 Producto X")
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.code_batches IS 'Agrupa códigos de producto, usualmente para una campaña o lote de producto específico.';
COMMENT ON COLUMN public.code_batches.name IS 'Nombre identificativo para el lote de códigos.';

-- Códigos de Producto (Vinculados a un Lote)
CREATE TABLE public.product_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    code_value VARCHAR(100) UNIQUE NOT NULL, -- El código único GLOBAL
    status VARCHAR(20) DEFAULT 'available' NOT NULL CHECK (status IN ('available', 'used')), -- Estado del código: 'available' (disponible), 'used' (usado)
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    used_at TIMESTAMPTZ NULL, -- Timestamp de cuándo se usó el código para completar una encuesta
    used_in_response_id BIGINT NULL, -- Referencia a la SurveyResponse donde se usó (para trazabilidad)
    FOREIGN KEY (batch_id) REFERENCES public.code_batches(id) ON DELETE CASCADE
    -- FK a survey_responses se añade después
);
COMMENT ON TABLE public.product_codes IS 'Códigos de producto individuales y globalmente únicos que pertenecen a un lote. Usados para dar acceso a encuestas específicas.';
COMMENT ON COLUMN public.product_codes.batch_id IS 'Referencia al lote al que pertenece este código.';
COMMENT ON COLUMN public.product_codes.code_value IS 'La cadena de texto única del código.';
COMMENT ON COLUMN public.product_codes.status IS 'Indica si el código está disponible para ser usado o si ya fue consumido.';
COMMENT ON COLUMN public.product_codes.used_at IS 'Fecha y hora en que el código fue marcado como usado.';
COMMENT ON COLUMN public.product_codes.used_in_response_id IS 'Vincula este código a la sesión de respuesta específica que lo consumió.';
CREATE INDEX idx_product_codes_batch_id ON public.product_codes(batch_id); -- Para buscar códigos por lote

-- Tabla de Enlace Lotes <-> Encuestas (Muchos a Muchos)
CREATE TABLE public.survey_code_batches (
    survey_id BIGINT NOT NULL,
    batch_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL, -- Añadido para trazabilidad opcional
    FOREIGN KEY (survey_id) REFERENCES public.surveys(id) ON DELETE CASCADE,
    FOREIGN KEY (batch_id) REFERENCES public.code_batches(id) ON DELETE CASCADE,
    PRIMARY KEY (survey_id, batch_id) -- Asegura que una encuesta solo se vincule una vez a un lote
);
COMMENT ON TABLE public.survey_code_batches IS 'Vincula los lotes de códigos con las encuestas a las que dan acceso (Relación Muchos a Muchos).';

-- Respuestas de los Clientes a una Encuesta
CREATE TABLE public.survey_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id BIGINT NOT NULL,
    customer_id BIGINT NULL, -- FK a tabla 'customers' (para agregación futura)
    product_code_id BIGINT NULL, -- FK al código específico usado para entrar (si aplica)
    start_time TIMESTAMPTZ DEFAULT now() NOT NULL,
    completion_time TIMESTAMPTZ NULL, -- Timestamp cuando se marca como 'completed'
    last_saved_section_id BIGINT NULL, -- Guarda la última sección en la que estuvo el usuario (para retomar)
    status VARCHAR(20) DEFAULT 'in_progress' NOT NULL CHECK (status IN ('in_progress', 'completed', 'abandoned')), -- Estado del proceso de respuesta: 'in_progress' (en curso), 'completed' (completada), 'abandoned' (abandonada)
    discount_percentage_achieved INT DEFAULT 0 NOT NULL, -- El % de descuento final calculado al completar
    generated_discount_code VARCHAR(100) NULL, -- El código de descuento final generado
    customer_name VARCHAR(255) NULL, -- Datos opcionales recopilados directamente
    customer_email VARCHAR(255) NULL,
    customer_phone VARCHAR(50) NULL,
    customer_wants_offers BOOLEAN NULL, -- Consentimiento para marketing
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    FOREIGN KEY (survey_id) REFERENCES public.surveys(id) ON DELETE CASCADE,
    FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL,
    FOREIGN KEY (product_code_id) REFERENCES public.product_codes(id) ON DELETE SET NULL,
    FOREIGN KEY (last_saved_section_id) REFERENCES public.survey_sections(id) ON DELETE SET NULL
);
COMMENT ON TABLE public.survey_responses IS 'Representa una única instancia de un cliente respondiendo a una encuesta.';
COMMENT ON COLUMN public.survey_responses.survey_id IS 'Referencia a la encuesta que se está respondiendo.';
COMMENT ON COLUMN public.survey_responses.customer_id IS 'Referencia al perfil del cliente potencial (si se identificó).';
COMMENT ON COLUMN public.survey_responses.product_code_id IS 'Referencia al código de producto específico que se usó para acceder (si aplica).';
COMMENT ON COLUMN public.survey_responses.status IS 'Rastrea el progreso de la respuesta de la encuesta.';
COMMENT ON COLUMN public.survey_responses.discount_percentage_achieved IS 'Porcentaje de descuento final obtenido por el cliente.';
COMMENT ON COLUMN public.survey_responses.generated_discount_code IS 'Código de descuento generado si la encuesta fue completada.';
COMMENT ON COLUMN public.survey_responses.customer_wants_offers IS 'Indica si el cliente aceptó recibir comunicaciones de marketing.';
COMMENT ON COLUMN public.survey_responses.last_saved_section_id IS 'ID de la última sección guardada por el usuario para poder retomar la encuesta.';

-- Añadir la FK de product_codes a survey_responses después de que ambas tablas existan
ALTER TABLE public.product_codes ADD CONSTRAINT fk_product_codes_response FOREIGN KEY (used_in_response_id) REFERENCES public.survey_responses(id) ON DELETE SET NULL;

-- Respuestas individuales a cada Pregunta (Incluye respuestas en progreso y finalizadas)
CREATE TABLE public.answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    answer_value TEXT NULL, -- La respuesta dada (puede ser NULL si se visitó pero no se respondió)
    question_text_at_response TEXT NOT NULL, -- Snapshot del texto de la pregunta al momento de responder
    question_type_at_response VARCHAR(50) NOT NULL, -- Snapshot del tipo de pregunta al momento de responder
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL, -- Timestamp de cuándo se guardó esta respuesta específica
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    FOREIGN KEY (response_id) REFERENCES public.survey_responses(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE, -- Se relaciona con la pregunta original
    UNIQUE(response_id, question_id) -- Solo una respuesta por pregunta dentro de una sesión de respuesta
);
COMMENT ON TABLE public.answers IS 'Almacena la respuesta individual proporcionada para cada pregunta dentro de una sesión de respuesta de encuesta. Incluye una "foto" de los detalles de la pregunta.';
COMMENT ON COLUMN public.answers.response_id IS 'Referencia a la sesión de respuesta general.';
COMMENT ON COLUMN public.answers.question_id IS 'Referencia a la definición original de la pregunta.';
COMMENT ON COLUMN public.answers.answer_value IS 'El valor real de la respuesta proporcionada por el usuario.';
COMMENT ON COLUMN public.answers.question_text_at_response IS '"Snapshot" (foto) del texto de la pregunta en el momento en que se respondió.';
COMMENT ON COLUMN public.answers.question_type_at_response IS '"Snapshot" (foto) del tipo de pregunta en el momento en que se respondió.';

-- Códigos de Descuento Generados (Auditoría)
CREATE TABLE public.discount_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id BIGINT NOT NULL,
    code_value VARCHAR(100) UNIQUE NOT NULL, -- El código de descuento generado
    percentage INT NOT NULL, -- El porcentaje de descuento asociado
    expiry_date DATE NOT NULL, -- Fecha de caducidad calculada
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    FOREIGN KEY (response_id) REFERENCES public.survey_responses(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.discount_codes IS 'Registra los códigos de descuento generados al completar encuestas para fines de auditoría.';
COMMENT ON COLUMN public.discount_codes.response_id IS 'Referencia a la respuesta de encuesta que generó este código.';
COMMENT ON COLUMN public.discount_codes.code_value IS 'El código de descuento único.';
COMMENT ON COLUMN public.discount_codes.percentage IS 'El porcentaje de descuento otorgado.';
COMMENT ON COLUMN public.discount_codes.expiry_date IS 'Fecha hasta la cual el código de descuento es válido.';
CREATE INDEX idx_discount_codes_response_id ON public.discount_codes(response_id);